language: c

env:
  matrix:
    - TF_VERSION=0.10.7
    - TF_VERSION=0.10.4

before_install:
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

script:
  - terraform init
  - terraform fmt -diff=true
  - terraform validate -check-variables=false
  